puppetlabs/puppet-dev-tools

Rakefile
`site-modules` is the new standard directory name for local modules in the control repo.
=> Excluding plans under site-modules

Dockerfile
Used more up-to-date git package from the RedHat software collections library.
This helps when using this image as the basis for a VS Code Dev Container, since otherwise VS Code complains that git is too old.
=> Updated git to rhscl version 2.18

build.sh, gosu/Dockerfile
Previous to this commit, Continuous Delivery for PE would install the
gosu package on every single job run for Docker based jobs. This commit
bakes the gosu package into the image so it doesn't have to be
downloaded each time and can operate behind air-gapped firewalls.
Further, to help faciliate building multiple images, this commit
introduces a build.sh script that builds multiple images at the same
time
=> Add image tag with gosu

Dockerfile
As per my comments in issue #10, this saves ~360MB.
```
$ docker images | grep puppet-dev-tools
tommythekid/puppet-dev-tools                                    latest                        9801083f16d7        23 hours ago        1.06GB
tommythekid/puppet-dev-tools                                    <none>                        4c270f1497a4        44 hours ago        1.1GB
puppet/puppet-dev-tools                                         latest                        02287227c5bf        13 days ago         1.42GB
```
NOTE: The untagged one in the middle is without the combined yum commands (~40MB)
=> Fixes #10 - Cleanup after package install

Rakefile
Previous to this PR, the latest ra10ke gem was breaking Puppetfile syntax validation due to a change in the way the gem's rake tasks are loaded. This PR properly loads the rake tasks in the Rakefile so that the r10k::syntax task is restored.
=> Fix ra10ke tasks

Rakefile
Previous to this commit, the list of paths to exclude from linting and
parser validation was static. For users that have Bolt plans, for
example, that need to be excluded from the syntax and linting checks,
there was no way to do so.
This commit provides the EXCLUDE_PATHS environment variable, deliniated
by ':' characters, to provide a list of paths to exclude from linting
and syntax checks.
For example: `export EXCLUDE_PATHS=modules/**/plans/*:site/modules/**/bad_code/*`
=> Provide a way to exclude syntax/lint paths

Dockerfile, Gemfile
The ffi gem think mkdir should be in /usr/bin/mkdir when it is in fact located at /bin/mkdir. This commit creates a symlink from one to the other. It also adds the ffi gem to the Gemfile so that its native extensions are already built.
=> Fix build of ffi / symlink mkdir

Dockerfile
This change is intended to resolve issues where Onceover was throwing errors due to non US-ASCII characters in modules.
=> Update locale to en_US.UTF-8

Gemfile
This version supports having a `spec/r10k.yaml` file with things like pool_size and baseurl defined.
=> Bump Onceover to 3.16

tests/control-repo/goodsyntax/manifests/site.pp, tests/control-repo/goodsyntax/site/profile/manifests/common.pp, tests/run_tests.sh
This PR adds tests for the corresponding new linting check in the code validation CD4PE stage. The files in the `goodsyntax/` testing directory have also been updated to pass the check.
=> (DIO-679) Add tests for running linter

Gemfile
It would be really useful if we could run onceover with the --parallel flag to run tests in parallel.
For customers in air gapped environments we need the gem to be included in the docker container.
I've added it to the Gemfile and tested by own build of the container and it allows onceover to run in parallel without needing internet access.
=> Added parallel 1.19.2 to the Gemfile

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml
Stops publishing gosu images, they're no longer supported or needed.
Start publishing all new images as part of a 4.x series to coincide with the up-coming CD4PE 4.0 release.
=> Stop publishing gosu images, publish new releases as 4.x series

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, Dockerfile, README.md, build-rootless.sh
The default output of the Dockerfile is still an image that runs as root, but now there is an option to produce one that runs as "puppetdev" instead. A second build script was added that outputs an image from before the build process switches back to root.
=> Create rootless and root-based images

Dockerfile
Previous to this PR, the apt cache was not updated prior to doing an apt package upgrade. This caused important updates to be missed. This commit introduces an initial apt cache update prior to doing an apt upgrade. Another apt cache update is one after the puppet agent repository package is installed.
=> Fix apt package upgrades

.github/workflows/publish-4x-image.yml
With this commit, we add a Github action to take a dev image (and
rootless dev image) and promote them to 4.x and 4.x-rootless,
respectively. This action is to be used by automation in the Pipelines
Infra repo to promote test images to the 4.x tag before each release
in order to release puppet-dev-tools monthly. See
https://tickets.puppetlabs.com/browse/CDPE-4314 for more details.
=> (CDPE-4329) Github action to promote 4.x image

Dockerfile
With this commit, we remove a handful of "sensitive" test files that are
left on disk as part of our Docker build process. These files don't pose
a real security threat, but the customer has requested we remove them,
and we have agreed.
=> (CDPE-4810) Remove sensitive test files per customer request

Dockerfile
This also adds a splat to our removal of puppet-7.x.x test fixtures in
the Dockerfile since we don't want to try and keep up with every y release of the
puppet gem. This removal comes from another customer ask.
Also, we are removing a bunch of files (at the behest of aforementioned customer) in a
separate layer at the end of our Dockerfile. TIL it's not that huge of a lift to
go back a few layers and grab those files from the docker image.
So. This moves the removal commands into the same layers that create the
files so that they are never present in the image, even on layer introspection.
=> (CDPE-4856) Remove more puppet gem keys in Dockerfile

README.md
This might not be the ultimate solution for why the docker container doesn't run properly; I'm not a developer.
Someone smarter than me can probably find the ultimate fix but changing the documentation so that the linter works is a short-term solution for guys like me that just want to check their puppet code.
=> Update README.md to reflect proper syntax for docker container

Dockerfile
We were encountering a couple CVEs with the 2.7.4-slim-buster image (CVE-2022-29155, CVE-2022-1664, CVE-2022-1292, and CVE-2022-29824), all OS level issues. These could be patched by trying to upgrade each software individually, but upgrading the whole base image seemed like the easier and better decision (2.7.4-slim-buster is no longer 'supported'). c
----
Trivy was tagging a few more files in the puppet gem spec directory as security risks. Instead of trying to pick out individual spec files, this just removes all the spec directories for puppet gems in the image.
=> Security updates alongside CD4PE 4.15.0

.github/workflows/snyk.yml
Currently, our snyk action reports to the foss project with the SNYK_FOSS_KEY but we want to see it in our snyk project, since we're the primary maintainers and it'll make visibility much better for us, so this commit changes the snyk command to use SNYK_CD4PE_KEY instead.
=> (maint) Change Snyk key to SNYK_CD4PE_KEY

.github/workflows/build-test-push.yml, .github/workflows/publish-4x-image.yml
Trivy is our official container scanning solution now, so this adds a
trivy scan whenever we try to push a new puppet-dev-tools container so
we don't release containers with unwanted vulnerabilities.
Trivy only scans the root-based image to save time as there are no
os-level differences between root and rootless images.
----
This adds a Trivy scan to the 4.x publish action. Since vulnerabilities
can be discovered at any time, we want to double check the dev image before we
publish to 4.x. As part of adding the Trivy step, this also splits out
the docker pull part of the action, which saves time on the Trivy scan that was timing out.
=> Add Trivy scans to github actions

.github/workflows/build-test-push.yml, .github/workflows/publish-4x-image.yml
Adds a timeout of 10 minutes (default is 5 min) to get around transient timeout failures
=> (maint) bump Trivy scan timeout in Build-Test-Push action

Dockerfile
We don't want to release PDK 3.0.0 yet in puppet-dev-tools, so to prevent automatic upgrades with our build process, this change pins the PDK version to the current 2.x version.
=> (maint) pin PDK version to 2.7.1

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, Dockerfile
We currently pin our Ruby version in this Dockerfile to 2.7.4, so we also need to pin bundler to a version compatible with that. Updating the Ruby version is a bigger project that would need to be looked into separately.
=> (maint) Pin bundler to 2.4.22, which supports Ruby 2.7.4

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, .github/workflows/publish-4x-image.yml
Add a file skip to the publish job, remove the nokogiri skip as it appears to no longer be needed.
=> (maint) Update file skips for trivy

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, .github/workflows/publish-4x-image.yml
This allows the files with false positives to be skipped even if the Ruby or gem version changes.
=> (maint) Add globbing to Trivy skip-file directives

.github/workflows/build-test.yml
So we can invoke it from our release automation in PipelinesInfra.
=> (CDPE-6528) Make Build-Test job callable

.github/workflows/build-test-push.yml
Add optional input to the Build-Test-Push job for supplying an image tag to create in addition to the latest and timestamp-sha tags.
This enables workflows to call this and reliable know the name of the resulting image, and is a result of that fact that GitHub does not have a native way to run a workflow on a remote repository and get some sort of string-like output from it.
Since there's no way to get data back from the called workflow, instead let the calling workflow decide what name to use for the image tag.
Overall this enables this workflow to be called in automation by the CD4PE release workflows so the developer doing the CD4PE release doesn't have to manually trigger this first, find the image tag it created, then supply that image tag to a different workflow.
=> (CDPE-6528) Input image tag name to Build-Test-Push

Dockerfile
The last version of docker_dev-tools:puppet8 had pdk 3.0.1 installed, I think this was the only one available when I started working on it. PDK 3.2 is available and a customer has asked if we can update the image to reflect that.
=> updated to the latest version of pdk

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, .github/workflows/publish-4x-image.yml
The Trivy github action is currently experiencing a GCR rating limiting issue pulling its vulnerability DB
(https://github.com/aquasecurity/trivy-action/issues/389).  Until that issue is resolved, or we work out a way to host it ourselves, this commit will disable the scans.
In the meantime, we will have to run these scans manually.
=> (maint) Temporarily disable trivy scans due to rate limiting

.github/workflows/update-trivy-cache.yml
In order to avoid ratelimiting issues when running trivy scans, all trivy runs need to run against a local copy of the DB (rather than downloading it each time). This commit adds a workflow to download the trivy DBs each morning.
Once this is in place and runs at least once, the trivy scans can be added back in and set to use the cache rather than download.
This PR is essentially following the documented steps at https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch
=> (CDPE-7069) Start caching trivy DBs in separate workflow

.github/workflows/build-test-push.yml, .github/workflows/build-test.yml, .github/workflows/publish-4x-image.yml
This commit reverts the change to remove trivy scans.  In order to avoid the rate limiting errors that prompted their removal, this commit switches the trivy scans over to using a local cache of their DB.  That DB is refreshed daily via a separate workflow.
=> (CDPE-7069) Update trivy calls to use cache

.github/workflows/build-test-push.yml, .github/workflows/publish-4x-image.yml
IT just blessed us with an OAT that will allow us to push to puppet/puppet-dev-tools on dockerhub again. This switches our actions over to use the token instead of our password per dockerhubs docs here https://docs.docker.com/security/for-admins/access-tokens/#use-an-organization-access-token
=> (maint) Update GH actions to use DOCKERHUB_TOKEN (puppet8)
